// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsEXO5Gq-eBb5far4gpKlnAH5R4E_AVh4',
    appId: '1:775337050090:web:c8ab701e237e86414a7c93',
    messagingSenderId: '775337050090',
    projectId: 'trade-home-app',
    authDomain: 'trade-home-app.firebaseapp.com',
    storageBucket: 'trade-home-app.appspot.com',
    measurementId: 'G-MCT03V4HJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4B6DuXk2wtuAczy_afJOhodZvg6iYVZ4',
    appId: '1:775337050090:android:f0cb43c0688f671f4a7c93',
    messagingSenderId: '775337050090',
    projectId: 'trade-home-app',
    storageBucket: 'trade-home-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRX_Ov4RZPHvacvKCp6WCMmVxx6JRrfLc',
    appId: '1:775337050090:ios:54a7c22abe4aec714a7c93',
    messagingSenderId: '775337050090',
    projectId: 'trade-home-app',
    storageBucket: 'trade-home-app.appspot.com',
    iosBundleId: 'com.example.tradeHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRX_Ov4RZPHvacvKCp6WCMmVxx6JRrfLc',
    appId: '1:775337050090:ios:e88f7d8cb4389e954a7c93',
    messagingSenderId: '775337050090',
    projectId: 'trade-home-app',
    storageBucket: 'trade-home-app.appspot.com',
    iosBundleId: 'com.example.tradeHomeApp.RunnerTests',
  );
}
